name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: PHPStan analysis
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.2"
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"
      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"
      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Run PHPStan
        run: vendor/bin/phpstan analyze

  build-phar:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: SOF3/pharynx@v0.2
        id: pharynx
      - uses: actions/upload-artifact@v3
        with:
          name: SkyBlockPM-OC.phar
          path: ${{steps.pharynx.outputs.output-phar}}
      - uses: actions/upload-artifact@v3
        with:
          name: SkyBlockPM-OC
          path: ${{steps.pharynx.outputs.output-dir}}
